{"trial_id": "0", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "f", "default": null, "conditions": [], "min_value": 64, "max_value": 112, "step": 32, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "n", "default": null, "conditions": [], "min_value": 2, "max_value": 2, "step": 1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "m", "default": null, "conditions": [], "min_value": 3, "max_value": 5, "step": 1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "k", "default": null, "conditions": [], "min_value": 3, "max_value": 3, "step": 2, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "d", "default": null, "conditions": [], "min_value": 32, "max_value": 128, "step": 32, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "p", "default": null, "conditions": [], "min_value": 2, "max_value": 5, "step": 2, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "dr", "default": 0.05, "conditions": [], "min_value": 0.05, "max_value": 0.09, "step": 0.02, "sampling": "linear"}}], "values": {"f": 64, "n": 2, "m": 4, "k": 3, "d": 96, "p": 4, "dr": 0.05}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/home/apakiman/anaconda3/envs/TF-keras/lib/python3.9/site-packages/keras_tuner/engine/base_tuner.py\", line 270, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/home/apakiman/anaconda3/envs/TF-keras/lib/python3.9/site-packages/keras_tuner/engine/base_tuner.py\", line 235, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/home/apakiman/anaconda3/envs/TF-keras/lib/python3.9/site-packages/keras_tuner/engine/tuner.py\", line 287, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"/home/apakiman/anaconda3/envs/TF-keras/lib/python3.9/site-packages/keras_tuner/engine/tuner.py\", line 213, in _build_and_fit_model\n    model = self._try_build(hp)\n  File \"/home/apakiman/anaconda3/envs/TF-keras/lib/python3.9/site-packages/keras_tuner/engine/tuner.py\", line 155, in _try_build\n    model = self._build_hypermodel(hp)\n  File \"/home/apakiman/anaconda3/envs/TF-keras/lib/python3.9/site-packages/keras_tuner/engine/tuner.py\", line 146, in _build_hypermodel\n    model = self.hypermodel.build(hp)\n  File \"/tmp/ipykernel_320940/2050365723.py\", line 33, in build_model\n    model = keras.Sequential(\n  File \"/home/apakiman/anaconda3/envs/TF-keras/lib/python3.9/site-packages/tensorflow/python/trackable/base.py\", line 204, in _method_wrapper\n    result = method(self, *args, **kwargs)\n  File \"/home/apakiman/anaconda3/envs/TF-keras/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/home/apakiman/anaconda3/envs/TF-keras/lib/python3.9/site-packages/tensorflow/python/framework/ops.py\", line 1751, in _create_c_op\n    raise ValueError(e.message)\nValueError: Exception encountered when calling layer \"max_pooling2d_3\" (type MaxPooling2D).\n\nNegative dimension size caused by subtracting 4 from 2 for '{{node max_pooling2d_3/MaxPool}} = MaxPool[T=DT_FLOAT, data_format=\"NHWC\", explicit_paddings=[], ksize=[1, 4, 4, 1], padding=\"VALID\", strides=[1, 4, 4, 1]](Placeholder)' with input shapes: [?,2,2,128].\n\nCall arguments received by layer \"max_pooling2d_3\" (type MaxPooling2D):\n  \u2022 inputs=tf.Tensor(shape=(None, 2, 2, 128), dtype=float32)\n"}